version: '3.0'

services:
  collector:
    build:
      context: ../collector
      dockerfile: collector.dockerfile
    image: smoke-collector
    volumes:
      - "data-volume:/var/lib"

  app:
    build:
      context: .
      dockerfile: app.dockerfile
    image: smoke-app
    ports:
      - '5000:5000'
    depends_on:
      - "collector"

  bats:
    build:
      context: .
      dockerfile: bats.dockerfile
    image: smoke-bats
    volumes:
      - "data-volume:/var/lib"
    depends_on:
      - "app"

volumes:
  data-volume:
